In [1]:
import numpy as np
import pandas as pd
import math
import warnings
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
warnings.filterwarnings('ignore')
df=pd.read_csv(r"adult_edited.data")

In [2]:
df = pd.get_dummies(df, columns=['workclass', 'education','marital-status','occupation','relationship','race','sex','native-country'])
a = pd.get_dummies(df.target, drop_first=True)
df = pd.concat([df, a], axis=1)
df = df.drop(['target'], axis = 1)
df

,age,fnlwgt,education-num,capital-gain,capital-loss,house-per-week,workclass_ ?,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Never-worked,...,native-country_ Puerto-Rico,native-country_ Scotland,native-country_ South,native-country_ Taiwan,native-country_ Thailand,native-country_ Trinadad&Tobago,native-country_ United-States,native-country_ Vietnam,native-country_ Yugoslavia,>50K
0,39,77516,13,2174,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,50,83311,13,0,0,13,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,38,215646,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,53,234721,7,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,28,338409,13,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,257302,12,0,0,38,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32557,40,154374,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
32558,58,151910,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32559,22,201490,9,0,0,20,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32560,52,287927,9,15024,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1

In [3]:
y = df[' >50K']
X = df.drop([' >50K'], axis = 1)
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=64)
logisticRegr = LogisticRegression()
logisticRegr.fit(x_train, y_train)
predictions = logisticRegr.predict(x_test)
print(predictions)
# score = logisticRegr.score(y_train, y_test)
# print(score)

[1 0 1 ... 0 0 0]

In [4]:
correct = 0
tp = 0
tn = 0
fp = 0
fn = 0



actual_df = y_test.to_numpy()

for i in range (len(predictions)):
    if predictions[i] == actual_df[i]:
        correct += 1
        if predictions[i] == ' <50k':
            tn += 1
        else:
            tp += 1
    else:
        if predictions[i] == ' <50k':
            fn += 1
        else:
            fp += 1



#Calculate the accuracy
accuracy = correct / len(predictions)
precision = tp/(tp + fp)
recall = tp/(tp + fn)
f1 = tp/(tp + 1/2*(fp+fn))

# Print the accuracy
print(fn)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall", recall)
print("F1 score", f1)

0
Accuracy: 0.7949934859482598
Precision: 0.7949934859482598
Recall 1.0
F1 score 0.885789828399606